classifiers:
  random_forest:
      class: sklearn.ensemble.RandomForestClassifier
      param_grid:
        n_estimators: [5, 100]  
        max_depth: [10, 20]  
        min_samples_split: [2, 5]
        min_samples_leaf: [1, 2]
        class_weight: ['balanced']  

  extra_trees:
    class: sklearn.ensemble.ExtraTreesClassifier
    param_grid:
      n_estimators: [16, 128]  
      max_depth: [1, 20]  
      min_samples_split: [2, 5]
      min_samples_leaf: [1, 2]
      class_weight: ['balanced']  

  ada_boost:
    class: sklearn.ensemble.AdaBoostClassifier
    param_grid:
      n_estimators: [16, 128]  
      learning_rate: [0.01, 0.1]  

  gradient_boost:
    class: sklearn.ensemble.GradientBoostingClassifier
    param_grid:
      n_estimators: [16, 128]  
      learning_rate: [0.01, 0.1]  
      max_depth: [3, 5]  

  xgboost:
    class: xgboost.XGBClassifier
    param_grid:
      n_estimators: [16, 128]  
      learning_rate: [0.01, 0.1]  
      max_depth: [0, 10]  
      subsample: [0.8, 1.0]
      colsample_bytree: [0.8, 1.0]
      device: ['cuda']
  lightgbm:
    class: lightgbm.LGBMClassifier
    param_grid:
      n_estimators: [16, 128]
      learning_rate: [0.01, 0.1]
      max_depth: [-1, 10]
      num_leaves: [31, 128]
      subsample: [0.8, 1.0]
      colsample_bytree: [0.8, 1.0]

  drm:
    class: rdm.custom_classifiers.prop_drm.PropDRM
    param_grid:
      num_epochs: [5, 50]
      learning_rate: [0.001, 0.01]
      hidden_layer_size: [16, 64]
      dropout: [0.1, 0.5]
