top_250_movies = [("The Shawshank Redemption", "1994", 1),
                   ("The Godfather", "1972", 1),
                   ("The Dark Knight", "2008", 1),
                   ("The Godfather Part II", "1974", 1),
                   ("Angry Men", "1957", 1),
                   ("Pulp Fiction", "1994", 1),
                   ("Forrest Gump", "1994", 1),
                   ("Fight Club", "1999", 1),
                   ("Inception", "2010", 1),
                   ("The Matrix", "1999", 1),
                   ("Goodfellas", "1990", 1),
                   ("Seven Samurai", "1954", 1),
                   ("Interstellar", "2014", 1),
                   ("The Silence of the Lambs", "1991", 1),
                   ("Saving Private Ryan", "1998", 1),
                   ("City of God", "2002", 1),
                   ("Life Is Beautiful", "1997", 1),
                   ("The Green Mile", "1999", 1),
                   ("Judgment Day", "1991", 1),
                   ("Back to the Future", "1985", 1),
                   ("Spirited Away", "2001", 1),
                   ("The Pianist", "2002", 1),
                   ("Psycho", "1960", 1),
                   ("Parasite", "2019", 1),
                   ("Gladiator", "2000", 1),
                   ("The Lion King", "1994", 1),
                   ("American History X", "1998", 1),
                   ("The Departed", "2006", 1),
                   ("Whiplash", "2014", 1),
                   ("The Prestige", "2006", 1),
                   ("The Usual Suspects", "1995", 1),
                   ("Grave of the Fireflies", "1988", 1),
                   ("Harakiri", "1962", 1),
                   ("Casablanca", "1942", 1),
                   ("Oppenheimer", "2023", 1),
                   ("The Intouchables", "2011", 1),
                   ("Modern Times", "1936", 1),
                   ("Cinema Paradiso", "1988", 1),
                   ("Once Upon a Time in the West", "1968", 1),
                   ("Rear Window", "1954", 1),
                   ("Alien", "1979", 1),
                   ("City Lights", "1931", 1),
                   ("Apocalypse Now", "1979", 1),
                   ("Memento", "2000", 1),
                   ("Django Unchained", "2012", 1),
                   ("Raiders of the Lost Ark", "1981", 1),
                   ("The Lives of Others", "2006", 1),
                   ("Paths of Glory", "1957", 1),
                   ("The Shining", "1980", 1),
                   ("The Great Dictator", "1940", 1),
                   ("Witness for the Prosecution", "1957", 1),
                   ("Aliens", "1986", 1),
                   ("Inglourious Basterds", "2009", 1),
                   ("The Dark Knight Rises", "2012", 1),
                   ("American Beauty", "1999", 1),
                   ("Oldboy", "2003", 1),
                   ("Coco", "2017", 1),
                   ("Amadeus", "1984", 1),
                   ("Toy Story", "1995", 1),
                   ("Das Boot", "1981", 1),
                   ("Braveheart", "1995", 1),
                   ("Joker", "2019", 1),
                   ("Princess Mononoke", "1997", 1),
                   ("Good Will Hunting", "1997", 1),
                   ("Once Upon a Time in America", "1984", 1),
                   ("High and Low", "1963", 1),
                   ("Capernaum", "2018", 1),
                   ("Requiem for a Dream", "2000", 1),
                   ("Come and See", "1985", 1),
                   ("Eternal Sunshine of the Spotless Mind", "2004", 1),
                   ("A Space Odyssey", "1968", 1),
                   ("The Hunt", "2012", 1),
                   ("Reservoir Dogs", "1992", 1),
                   ("Ikiru", "1952", 1),
                   ("Lawrence of Arabia", "1962", 1),
                   ("Citizen Kane", "1941", 1),
                   ("M", "1931", 1),
                   ("The Apartment", "1960", 1),
                   ("North by Northwest", "1959", 1),
                   ("Vertigo", "1958", 1),
                   ("Double Indemnity", "1944", 1),
                   ("Scarface", "1983", 1),
                   ("Full Metal Jacket", "1987", 1),
                   ("A Clockwork Orange", "1971", 1),
                   ("Incendies", "2010", 1),
                   ("Heat", "1995", 1),
                   ("Up", "2009", 1),
                   ("Hamilton", "2020", 1),
                   ("To Kill a Mockingbird", "1962", 1),
                   ("The Sting", "1973", 1),
                   ("A Separation", "2011", 1),
                   ("Indiana Jones and the Last Crusade", "1989", 1),
                   ("Metropolis", "1927", 1),
                   ("Die Hard", "1988", 1),
                   ("Like Stars on Earth", "2007", 1),
                   ("Snatch", "2000", 1),
                   ("Bicycle Thieves", "1948", 1),
                   ("Taxi Driver", "1976", 1),
                   ("Downfall", "2004", 1),
                   ("Dangal", "2016", 1),
                   ("For a Few Dollars More", "1965", 1),
                   ("Batman Begins", "2005", 1),
                   ("Some Like It Hot", "1959", 1),
                   ("The Kid", "1921", 1),
                   ("The Wolf of Wall Street", "2013", 1),
                   ("The Father", "2020", 1),
                   ("Green Book", "2018", 1),
                   ("All About Eve", "1950", 1),
                   ("Judgment at Nuremberg", "1961", 1),
                   ("The Truman Show", "1998", 1),
                   ("There Will Be Blood", "2007", 1),
                   ("Casino", "1995", 1),
                   ("Ran", "1985", 1),
                   ("Shutter Island", "2010", 1),
                   ("The Sixth Sense", "1999", 1),
                   ("Jurassic Park", "1993", 1),
                   ("Unforgiven", "1992", 1),
                   ("A Beautiful Mind", "2001", 1),
                   ("The Treasure of the Sierra Madre", "1948", 1),
                   ("Yojimbo", "1961", 1),
                   ("No Country for Old Men", "2007", 1),
                   ("Monty Python and the Holy Grail", "1975", 1),
                   ("The Thing", "1982", 1),
                   ("The Great Escape", "1963", 1),
                   ("Rashomon", "1950", 1),
                   ("Finding Nemo", "2003", 1),
                   ("The Elephant Man", "1980", 1),
                   ("Chinatown", "1974", 1),
                   ("Dial M for Murder", "1954", 1),
                   ("Gone with the Wind", "1939", 1),
                   ("V for Vendetta", "2005", 1),
                   ("Raging Bull", "1980", 1),
                   ("Prisoners", "2013", 1),
                   ("The Secret in Their Eyes", "2009", 1),
                   ("Inside Out", "2015", 1),
                   ("The Bridge on the River Kwai", "1957", 1),
                   ("Trainspotting", "1996", 1),
                   ("Fargo", "1996", 1),
                   ("Warrior", "2011", 1),
                   ("Gran Torino", "2008", 1),
                   ("Catch Me If You Can", "2002", 1),
                   ("My Neighbor Totoro", "1988", 1),
                   ("Million Dollar Baby", "2004", 1),
                   ("Klaus", "2019", 1),
                   ("Children of Heaven", "1997", 1),
                   ("Blade Runner", "1982", 1),
                   ("Years a Slave", "2013", 1),
                   ("Before Sunrise", "1995", 1),
                   ("The Grand Budapest Hotel", "2014", 1),
                   ("The Gold Rush", "1925", 1),
                   ("Gone Girl", "2014", 1),
                   ("Barry Lyndon", "1975", 1),
                   ("Hacksaw Ridge", "2016", 1),
                   ("On the Waterfront", "1954", 1),
                   ("In the Name of the Father", "1993", 1),
                   ("Memories of Murder", "2003", 1),
                   ("The General", "1926", 1),
                   ("The Deer Hunter", "1978", 1),
                   ("Wild Strawberries", "1957", 1),
                   ("The Third Man", "1949", 1),
                   ("Wild Tales", "2014", 1),
                   ("The Wages of Fear", "1953", 1),
                   ("Dead Poets Society", "1989", 1),
                   ("Jaws", "1975", 1),
                   ("How to Train Your Dragon", "2010", 1),
                   ("Mary and Max", "2009", 1),
                   ("The Seventh Seal", "1957", 1),
                   ("Ford v Ferrari", "2019", 1),
                   ("Room", "2015", 1),
                   ("The Big Lebowski", "1998", 1),
                   ("Tokyo Story", "1953", 1),
                   ("Ratatouille", "2007", 1),
                   ("Rocky", "1976", 1),
                   ("Hotel Rwanda", "2004", 1),
                   ("Logan", "2017", 1),
                   ("The Passion of Joan of Arc", "1928", 1),
                   ("Spotlight", "2015", 1),
                   ("Platoon", "1986", 1),
                   ("The Terminator", "1984", 1),
                   ("Jai Bhim", "2021", 1),
                   ("Before Sunset", "2004", 1),
                   ("Rush", "2013", 1),
                   ("Network", "1976", 1),
                   ("Stand by Me", "1986", 1),
                   ("The Best Years of Our Lives", "1946", 1),
                   ("The Exorcist", "1973", 1),
                   ("La haine", "1995", 1),
                   ("The Wizard of Oz", "1939", 1),
                   ("Into the Wild", "2007", 1),
                   ("The Incredibles", "2004", 1),
                   ("My Father and My Son", "2005", 1),
                   ("To Be or Not to Be", "1942", 1),
                   ("The Handmaiden", "2016", 1),
                   ("The Grapes of Wrath", "1940", 1),
                   ("Groundhog Day", "1993", 1),
                   ("The Battle of Algiers", "1966", 1),
                   ("Amores Perros", "2000", 1),
                   ("Rebecca", "1940", 1),
                   ("The Sound of Music", "1965", 1),
                   ("Cool Hand Luke", "1967", 1),
                   ("Pather Panchali", "1955", 1),
                   ("The Iron Giant", "1999", 1),
                   ("It Happened One Night", "1934", 1),
                   ("The Help", "2011", 1),
                   ("Blows", "1959", 1),
                   ("Persona", "1966", 1),
                   ("Life of Brian", "1979", 1),
                   ("Aladdin", "1992", 1),
                   ("Dances with Wolves", "1990", 1)]

bottom_100_movies = [("Disaster Movie", "2008", 0),
                      ("Manos: The Hands of Fate", "1966", 0),
                      ("Birdemic: Shock and Terror", "2010", 0),
                      ("Superbabies: Baby Geniuses 2", "2004", 0),
                      ("The Hottie & the Nottie", "2008", 0),
                      ("Kirk Cameron's Saving Christmas", "2014", 0),
                      ("House of the Dead", "2003", 0),
                      ("Son of the Mask", "2005", 0),
                      ("Epic Movie", "2007", 0),
                      ("Radhe", "2021", 0),
                      ("Battlefield Earth", "2000", 0),
                      ("Pledge This!", "2006", 0),
                      ("Alone in the Dark", "2005", 0),
                      ("Dragonball Evolution", "2009", 0),
                      ("Race 3", "2018", 0),
                      ("From Justin to Kelly", "2003", 0),
                      ("Foodfight!", "2012", 0),
                      ("Going Overboard", "1989", 0),
                      ("Turks in Space", "2006", 0),
                      ("Meet the Spartans", "2008", 0),
                      ("Gigli", "2003", 0),
                      ("Date Movie", "2006", 0),
                      ("Daniel the Wizard", "2004", 0),
                      ("Cats", "2019", 0),
                      ("Baby Geniuses", "1999", 0),
                      ("Glitter", "2001", 0),
                      ("The Human Centipede III (Final Sequence)", "2015", 0),
                      ("Cosmic Sin", "2021", 0),
                      ("Jaws: The Revenge", "1987", 0),
                      ("Troll 2", "1990", 0),
                      ("BloodRayne", "2005", 0),
                      ("Mega Shark vs. Giant Octopus", "2009", 0),
                      ("3Days: This Day", "2022", 0),
                      ("Hobgoblins", "1988", 0),
                      ("Jeepers Creepers: Reborn", "2022", 0),
                      ("Left Behind", "2014", 0),
                      ("3Days", "2020", 0),
                      ("The Cost of Deception", "2021", 0),
                      ("Enes Batur: Imagination or Reality?", "2018", 0),
                      ("Who's Your Caddy?", "2007", 0),
                      ("Jack and Jill", "2011", 0),
                      ("Rollerball", "2002", 0),
                      ("Santa Claus Conquers the Martians", "1964", 0),
                      ("Adipurush", "2023", 0),
                      ("Slender Man", "2018", 0),
                      ("Catwoman", "2004", 0),
                      ("Kazaam", "1996", 0),
                      ("Winnie the Pooh: Blood and Honey", "2023", 0),
                      ("Vampires Suck", "2010", 0),
                      ("The Emoji Movie", "2017", 0),
                      ("Student of the Year 2", "2019", 0),
                      ("Steel", "1997", 0),
                      ("The Starving Games", "2013", 0),
                      ("The Open House", "2018", 0),
                      ("Laxmii", "2020", 0),
                      ("Breach", "2020", 0),
                      ("Tees Maar Khan", "2010", 0),
                      ("Scary Movie V", "2013", 0),
                      ("Dumb and Dumberer: When Harry Met Lloyd", "2003", 0),
                      ("Texas Chainsaw Massacre: The Next Generation", "1994", 0),
                      ("Gunday", "2014", 0),
                      ("The Room", "2003", 0),
                      ("The Master of Disguise", "2002", 0),
                      ("Police Academy: Mission to Moscow", "1994", 0),
                      ("Daddy Day Camp", "2007", 0),
                      ("Bratz", "2007", 0),
                      ("Hercules in New York", "1970", 0),
                      ("Far Cry", "2008", 0),
                      ("Mortal Kombat: Annihilation", "1997", 0),
                      ("Feardotcom", "2002", 0),
                      ("Barb Wire", "1996", 0),
                      ("Smolensk", "2016", 0),
                      ("3 Ninjas: High Noon at Mega Mountain", "1998", 0),
                      ("Baaghi 3", "2020", 0),
                      ("Batman & Robin", "1997", 0),
                      ("Fifty Shades of Black", "2016", 0),
                      ("Captain America", "1990", 0),
                      ("Spy Kids All the Time in the World", "2011", 0),
                      ("Crossroads", "2002", 0),
                      ("The NeverEnding Story III", "1994", 0),
                      ("Jaws 3-D", "1983", 0),
                      ("Superman IV: The Quest for Peace", "1987", 0),
                      ("Spice World", "1997", 0),
                      ("Dungeons & Dragons", "2000", 0),
                      ("The Wicker Man", "2006", 0),
                      ("Black Christmas", "2019", 0),
                      ("The Fog", "2005", 0),
                      ("Dragon Wars: D-War", "2007", 0),
                      ("Mac and Me", "1988", 0),
                      ("I'll Always Know What You Did Last Summer", "2006", 0),
                      ("Bucky Larson: Born to Be a Star", "2011", 0),
                      ("Goal! III", "2009", 0),
                      ("Piranha 3DD", "2012", 0),
                      ("I Know Who Killed Me", "2007", 0),
                      ("The Adventures of Sharkboy and Lavagirl 3-D", "2005", 0),
                      ("The Love Guru", "2008", 0),
                      ("The Hungover Games", "2014", 0),
                      ("In the Name of the King: A Dungeon Siege Tale", "2007", 0),
                      ("The Avengers", "1998", 0),
                      ("The Flintstones in Viva Rock Vegas", "2000", 0)]
